程式/Enrollment/Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using Newtonsoft.Json;

namespace Enrollment.Models
{
    [JsonObject(MemberSerialization.OptIn)]
    public class Member : BackendBase
    {

        [Key]
        [Display(Name = "編號")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonProperty]
        public int Id { get; set; }

        [Required(ErrorMessage = "{0}必填")]
        [MaxLength(50)]
        [Display(Name = "帳號")]
        [JsonProperty]
        public string Account { get; set; }

        [Required(ErrorMessage = "{0}必填")]
        [StringLength(100, ErrorMessage = "{0} 長度至少必須為 {2} 個字元。", MinimumLength = 4)]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }

        [MaxLength(100)]
        [Display(Name = "密碼鹽")]
        public string PasswordSalt { get; set; }

        [Required(ErrorMessage = "{0}必填")]
        [MaxLength(50)]
        [Display(Name = "姓名")]
        public string Name { get; set; }

        [Required(ErrorMessage = "{0}必填")]
        [MaxLength(10)]
        [Display(Name = "身分證字號")]
        public string IDNum { get; set; }

        [MaxLength(50)]
        [Display(Name = "手機")]
        public string Mobile { get; set; }



        [Display(Name = "備註")]
        public string Memo { get; set; }

        [Display(Name = "性別")]
        [JsonProperty]
        public GenderType Gender { get; set; }

        [Required(ErrorMessage = "{0}必填")]
        [EmailAddress(ErrorMessage = "{0} 格式錯誤")]
        [MaxLength(200)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "E-Mail")]
        public string Email { get; set; }

        [MaxLength(50)]
        [Display(Name = "照片")]
        public string MyPic { get; set; }

        [MaxLength(50)]
        [Display(Name = "職稱")]

        public string JobTitle { get; set; }

        [MaxLength(200)]
        [Display(Name = "住址")]
        public string Address { get; set; }


        //ForeignKey
        [Display(Name = "單位")]
        public int UnitId { get; set; }


        [ForeignKey("UnitId")]
        public virtual Unit MyUnit { get; set; }



        [Display(Name = "角色")]
        public virtual ICollection<Role> Roles { get; set; }



        [MaxLength(500)]
        [Display(Name = "權限")]
        [JsonProperty]
        public string Permission { get; set; }

        public bool AddMember()
        {
            BackendContext db = new BackendContext();

            var pid = new SqlParameter { ParameterName = "Id", Value = 0, Direction = ParameterDirection.Output };
            var result =
                db.Members.SqlQuery(
                    "dbo.CreateMember @Account,@Password,@PasswordSalt,@Name,@IDNum,@Email,@JobTitle,@Permission,@Poster,@UnitId,@Gender,@MyPic,@Id out",
                    new SqlParameter("Account", this.Account), new SqlParameter("Password", this.Password),
                    new SqlParameter("@PasswordSalt", this.PasswordSalt),
                    new SqlParameter("Name", this.Name),
                    new SqlParameter("IDNum", this.IDNum),
                    new SqlParameter("Email", this.Email), new SqlParameter("JobTitle", this.JobTitle),
                    new SqlParameter("Permission", this.Permission),
                    new SqlParameter("Poster", "admin"), new SqlParameter("UnitId", this.UnitId),
                    new SqlParameter("Gender", this.Gender),
                    new SqlParameter("MyPic", this.MyPic ?? ""), pid).SingleOrDefault();
            return pid.Value.ToString() != "0";
        }




    }



    public class MemberLogin
    {
        [Required]
        [Display(Name = "使用者名稱")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }
    }

    public class MemberChangePassword
    {
        [Required]
        [StringLength(100, ErrorMessage = "{0} 長度至少必須為 {2} 個字元。", MinimumLength = 4)]
        [DataType(DataType.Password)]
        [Display(Name = "新密碼")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "確認新密碼")]
        [Compare("NewPassword", ErrorMessage = "新密碼與確認密碼不相符。")]
        public string ConfirmPassword { get; set; }
    }

}

程式/Enrollment/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MvcPaging;
using Enrollment.Filters;
using Enrollment.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace Enrollment.Controllers
{
    [PermissionFilters]
    [Authorize]
    public class MemberController : _BaseController
    {
        private BackendContext db = new BackendContext();
        private const int DefaultPageSize = 15;
        //
        // GET: /Member/

        public ActionResult Index(int? page, FormCollection fc)
        {
          

            //記住搜尋條件
            GetCatcheRoutes(page, fc);

            //取得正確的頁面
            int currentPageIndex = getCurrentPage(page, fc);

          
            var members = db.Members.OrderByDescending(p => p.InitDate).AsQueryable();
         
            if (hasViewData("SearchByAccount"))
            {
                string SearchByAccount = getViewDateStr("SearchByAccount");
                members = members.Where(w => w.Account.Contains(SearchByAccount));

            }
            if (hasViewData("SearchByName"))
            {
                string searchByName = getViewDateStr("SearchByName");
                members = members.Where(w => w.Name.Contains(searchByName));
            }
            if (hasViewData("SearchByphone"))
            {
                string SearchByphone = getViewDateStr("SearchByphone");
                members = members.Where(w => w.Mobile.Contains(SearchByphone));
            }


          


            return View(members.OrderByDescending(p => p.InitDate).ToPagedList(currentPageIndex, DefaultPageSize));





            
        }


      


        //
        // GET: /Member/Details/5

      


        //
        // GET: /Member/Create
        public ActionResult Create()
        {
            ViewBag.Units = db.Units.ToList();
           

            return View();
        }
   
        //
        // POST: /Member/Create

        [HttpPost]
        public ActionResult Create(Member member, HttpPostedFileBase upfile)
        {
            if (ModelState.IsValid)
            {
                //上傳檔案
                if (upfile != null)
                {
                    member.MyPic = Utility.SaveUpFile(upfile);
                }
                member.PasswordSalt = Utility.CreateSalt();
                member.Password = Utility.GenerateHashWithSalt(member.Password, member.PasswordSalt);
                member.JobTitle = member.JobTitle ?? "";
                member.Permission = member.Permission ?? "";
                TimeZoneInfo TPZone = TimeZoneInfo.FindSystemTimeZoneById("Taipei Standard Time");
                DateTime NOWTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TPZone);
                member.InitDate= NOWTime;
                member.UpdateDate = NOWTime;
                member.Poster = User.Identity.Name;
                member.UpdateID= User.Identity.Name;
                if (string.IsNullOrEmpty(member.Mobile))
                {
                    member.Mobile = "";
                }

                if (!member.AddMember())
                {
                    ViewBag.Units = db.Units.ToList();
                    ViewBag.Message = "帳號重複!";
                    member.Password = "";
                    ViewBag.Units = db.Units.ToList();
                    return View(member);
                }

            

                return RedirectToAction("Index");
            }
            //db.Members.Add(member);
            //db.SaveChanges();

            ViewBag.Units = db.Units.ToList();
            return View(member);
        }






        //
        // GET: /Member/Edit/5

        public ActionResult Edit(string actionName, int id = 0)
        {
            ViewBag.Units = db.Units.ToList();
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            string strMenu = Utility.GetMenu(member.Permission);

            if (actionName == null)
            {
                actionName = "index";
            }
            ViewBag.actionName = actionName;

            ViewBag.TreeScript = strMenu;

            return View(member);
        }

        //
        // POST: /Member/Edit/5

        [HttpPost]
        public ActionResult Edit(Member member, string actionName)
        {

           

           //移除驗證
           ModelState.Remove("Account");
            ModelState.Remove("Password");
            member.Password = Request["NewPassword"] != "" ? Utility.GenerateHashWithSalt(Request["NewPassword"], member.PasswordSalt) : Request["hash"];
            member.Permission = member.Permission ?? "";
            if (ModelState.IsValid)
            {
                member.Update(db,db.Members);
                if (actionName == null)
                {
                    actionName = "index";
                }
                return RedirectToActionPermanent(actionName, null,
                    new { page = Request["page"] });
            }
            ViewBag.Units = db.Units.ToList();
            string strMenu = Utility.GetMenu(member.Permission);
            ViewBag.TreeScript = strMenu.Trim();
            return View(member);
        }

        //
        // GET: /Member/Delete/5

        public ActionResult Delete( string actionName,int id = 0)
        {
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            if (actionName == null)
            {
                actionName = "index";
            }
            ViewBag.actionName = actionName;
            return View(member);
        }

        //
        // POST: /Member/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string actionName)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            if (actionName == null)
            {
                actionName = "index";
            }
            return RedirectToAction(actionName);
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string userName, string password, string ReturnUrl)
        {
           
            if (ModelState.IsValid)
            {
                Member member = ValidateUser(userName, password);
                if (member != null)
                {
                    Utility.GetPerssion(member);
                    string userData = JsonConvert.SerializeObject(member);
                    Utility.SetAuthenTicket(userData, userName);
                    //string Permission = "," + member.Permission;

                    //SSO(member.Account, member.Permission);
                    Session["login"] = true;
                    return RedirectToAction("Index", "Home", new { ReturnUrl = ReturnUrl });
                }
                ViewBag.message = "登入失敗!";
                return View();
            }
            ViewBag.message = "登入失敗!";
            return View();

        }
    
     


        [HttpPost]
        [AllowAnonymous]
        public ActionResult MobileLogin(string userName, string password)
        {
            
                Member member = ValidateUser(userName, password);
                if (member != null)
                {
                    var role = member.Roles.Where(x => x.Subject == "供應商");
                    if (role.Any())
                    {
                      // Utility.GetPerssion(member);
                    //string userData = JsonConvert.SerializeObject(member);
                    //Utility.SetAuthenTicket(userData, userName);
                    return Content("登入成功!");
                    }
                    
                }

                return Content("登入失敗!");
            
           
        }







        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(string newPassword)
        {
            Member member = db.Members.SingleOrDefault(o => o.Account == User.Identity.Name);
            if (member != null)
            {

                member.Password = Utility.GenerateHashWithSalt(newPassword, member.PasswordSalt);
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.message = "修改成功";
                return View();
            }
            ViewBag.message = "修改失敗!請重新登入試試!!";
            return View();
        }
        public ActionResult Default()
        {
            return View();
        }


        private Member ValidateUser(string userName, string password)
        {
            Member member = db.Members.SingleOrDefault(o => o.Account == userName);
            if (member == null)
            {
                return null;
            }
            string saltPassword = Utility.GenerateHashWithSalt(password, member.PasswordSalt);
            return saltPassword == member.Password ? member : null;
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            System.Web.Security.FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }


   

        //輸出treeView javascript Code 
        public JavaScriptResult TreeScript(int id = 0)
        {

程式/Enrollment/Views/Member/ChangePassword.cshtml
@model Enrollment.Models.MemberChangePassword

@{
    ViewBag.Title = "修改密碼";
}

<h2>修改密碼</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>修改密碼</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.NewPassword)
        </div>
        <div class="editor-field">
             @Html.EditorFor(model => model.NewPassword)
            @Html.ValidationMessageFor(model => model.NewPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ConfirmPassword)
        </div>
        <div class="editor-field">
             @Html.EditorFor(model => model.ConfirmPassword)
            @Html.ValidationMessageFor(model => model.ConfirmPassword)
        </div>

        <p>
            <input type="submit" value="送出" /> @ViewBag.message 
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("回列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

程式/Enrollment/Views/Member/Create.cshtml
@using System.Collections

@using Enrollment.Models
@model Enrollment.Models.Member

@{
    ViewBag.Title = "新增帳號";
}

<h2 class="page-title"><i class="fa fa-pencil-square-o"></i>新增帳號</h2>

@using (Html.BeginForm("Create", "Member", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>會員帳號資料</legend>
<table class="table table-h">
    <tr>
        <th width="120">
            @Html.LabelFor(model => model.Account)
            
        </th>
        <td>
             @Html.EditorFor(model => model.Account)<input id="btnCheck" type="button" class="btn btn-primary" value="檢查帳號" />
            @Html.ValidationMessageFor(model => model.Account) <span>@ViewBag.Message</span>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Password)
            
        </th>
        <td>
             @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Name)
        </th>
        <td>
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.IDNum)
        </th>
        <td>
            @Html.EditorFor(model => model.IDNum)
            @Html.ValidationMessageFor(model => model.IDNum)
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Gender)
            
        </th>
        <td>
             @Html.DropDownListFor(model => model.Gender, new SelectList(Enum.GetValues(typeof(GenderType))))
            @Html.ValidationMessageFor(model => model.Gender)
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Email)
            
        </th>
        <td>
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </td>
    </tr>
   
    <tr style="display: none">
        <th>
            @Html.LabelFor(model => model.MyPic)
            
        </th>
        <td>
            <input type="file" name="upfile" />
            
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.JobTitle)
            
        </th>
        <td>
            @Html.EditorFor(model => model.JobTitle)
            @Html.ValidationMessageFor(model => model.JobTitle)
        </td>
    </tr>
    <tr style="display: none">
        <th>
            @Html.LabelFor(model => model.UnitId)

        </th>
        <td>
            @Html.DropDownListFor(model => model.UnitId, new SelectList(ViewBag.Units as IEnumerable, "Id", "Subject"))
            @Html.ValidationMessageFor(model => model.UnitId)
        </td>
    </tr>
    <tr>
    <th>@Html.LabelFor(model => model.Memo)</th>
    <td> @Html.TextAreaFor(model => model.Memo, new { @style = "height: 150px" })
            @Html.ValidationMessageFor(model => model.Memo)</td>
</tr>
  

</table>
     <div class="editor-field" style="display: none">
            @Html.LabelFor(model => model.Permission)
            <div id="tree3"></div>
            @Html.HiddenFor(model => model.Permission)
        </div>    

       
        
        <p>
            <input type="submit" value="儲存" class="btn btn-primary" />
             @Html.ActionLink("回列表", "Index")
        </p>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui.custom.js" type="text/javascript"></script>


    <link href="~/Content/themes/base/skin/ui.dynatree.css" rel="stylesheet" type="text/css" id="skinSheet">
    <script src="~/Scripts/jquery.dynatree.js" type="text/javascript"></script>
    <script src="~/Member/TreeScript/0" type="text/javascript"></script>
     <script>
         $(document).ready(function () {
             $("#btnCheck").click(function () {
                 if ($("#Account").val() == "") {
                     alert("帳號不可空白");
                     return;
                 }
                 $.get("CheckAccount", { userName: $("#Account").val() }).done(function (data) {

                     alert(data);

                 }).fail(function () { alert("連線錯誤!"); });
             });
         });
    </script>
}

程式/Enrollment/Views/Member/Default.cshtml
@{
    ViewBag.Title = "歡迎使用管理系統";
}

<h2>歡迎使用管理系統</h2>

程式/Enrollment/Views/Member/Delete.cshtml
@model Enrollment.Models.Member

@{
    ViewBag.Title = "Delete";
}

<h2 class="page-title"><i class="fa fa-pencil-square-o"></i>刪除</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Member</legend>
    
    <input type="hidden" name="actionName" value="@ViewBag.actionName" />
   <table class="table table-h">
    <tr>
        <th width="120">
         @Html.DisplayNameFor(model => model.Account)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.Account)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.Password)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.Password)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.Name)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.Name)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.Email)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.Email)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.JobTitle)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.JobTitle)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.MyUnit)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.MyUnit.Subject)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.Poster)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.Poster)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.UpdateID)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.UpdateID)
            
        </td>
    </tr>
    <tr>
        <th>
         @Html.DisplayNameFor(model => model.InitDate)
            
        </th>
        <td>
        @Html.DisplayFor(model => model.InitDate)
            
        </td>
    </tr>
   
    
</table>
</fieldset>

@using (Html.BeginForm()) {
<p>
     <input type="submit" value="刪除" class="btn btn-Delete" />

       
        @Html.ActionLink("回列表", "Index")
    </p>
}

程式/Enrollment/Views/Member/Details.cshtml
@model SNDA.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Member</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Account)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Account)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.JobTitle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.JobTitle)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MyUnit)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MyUnit.Subject)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Poster)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Poster)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Updater)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Updater)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.InitDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InitDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("回列表", "Index")
</p>

程式/Enrollment/Views/Member/Edit.cshtml
@using System.Collections

@using Enrollment.Models
@model Enrollment.Models.Member

@{
    ViewBag.Title = "Edit";
}

<h2 class="page-title"><i class="fa fa-pencil-square-o"></i>帳號管理</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Member</legend>

        @Html.HiddenFor(model => model.Id)
        <input type="hidden" name="actionName" value="@ViewBag.actionName" />

        <table class="table table-h">
    <tr>
        <th width="120">
            @Html.LabelFor(model => model.Account)
            
        </th>
        <td>
             @Html.DisplayFor(model => model.Account)
            @Html.HiddenFor(model => model.Account)

        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Password)
            
        </th>
        <td>
           @Html.Password("NewPassword")
            <input type="hidden" id="hash" name="hash" value="@(Model.Password)" >
            @Html.HiddenFor(model=>model.PasswordSalt)  
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Name)
            
        </th>
        <td>
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </td>
    </tr>
            <tr>
                <th>
                    @Html.LabelFor(model => model.IDNum)
            
                </th>
                <td>
                    @Html.EditorFor(model => model.IDNum)
                    @Html.ValidationMessageFor(model => model.IDNum)
                </td>
            </tr>

    <tr>
        <th>
            @Html.LabelFor(model => model.Gender)
            
        </th>
        <td>
              @Html.DropDownListFor(model => model.Gender, new SelectList(Enum.GetValues(typeof(GenderType))))
            @Html.ValidationMessageFor(model => model.Gender)
        </td>
    </tr>
  
    <tr style="display: none">
        <th>
            @Html.LabelFor(model => model.Mobile)
            
        </th>
        <td>
             @Html.EditorFor(model => model.Mobile)
            @Html.ValidationMessageFor(model => model.Mobile)
        </td>
    </tr>
  
    <tr>
        <th>
            @Html.LabelFor(model => model.Email)
            
        </th>
        <td>
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </td>
    </tr>
            <tr>
                <th>
                    @Html.LabelFor(model => model.JobTitle)

                </th>
                <td>
                    @Html.EditorFor(model => model.JobTitle)
                    @Html.ValidationMessageFor(model => model.JobTitle)
                </td>
            </tr>
              <tr>
     
    </tr>
  <tr style="display: none">
      <th>
            @Html.LabelFor(model => model.MyUnit)
          
      </th>
      <td>
           @Html.DropDownListFor(model => model.UnitId, new SelectList(ViewBag.Units as IEnumerable, "Id", "Subject"))
            @Html.ValidationMessageFor(model => model.UnitId)
      </td>
  </tr>
<tr>
    <th>@Html.LabelFor(model => model.Memo)</th>
    <td> @Html.TextAreaFor(model => model.Memo, new { @style = "height: 150px" })
            @Html.ValidationMessageFor(model => model.Memo)</td>
</tr>
</table>

        @{
           
    if (!string.IsNullOrEmpty( Model.MyPic))
    {
            <div class="editor-label">
                @Html.LabelFor(model => model.MyPic)
            </div>
            <div class="editor-field">
                <img src="~/upfiles/@Model.MyPic" width="100px"/>
            </div>
    }
        }


        <div class="editor-label">
        </div>
        <div class="editor-field">
            
        </div>

        <div class="editor-label">
        </div>
        <div class="editor-field">
           
        </div>
        
        <div class="editor-label">
            
        </div>
        <div class="editor-field">
           
        </div>

        <div class="editor-field" style="display: none">
            @Html.LabelFor(model => model.Permission)
            <div id="tree3"></div>
            @Html.HiddenFor(model => model.Permission)
        </div>
        @Html.HiddenFor(model => model.InitDate)
        @Html.HiddenFor(model => model.Poster)
        @Html.HiddenFor(model => model.MyPic)
        <div align="center">
            <input type="submit" value="更新" /> <input type="button" onclick="history.back()" value="回到上一頁" />
        </div>
    </fieldset>

}







@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui.custom.js" type="text/javascript"></script>


    <link href="~/Content/themes/base/skin/ui.dynatree.css" rel="stylesheet" type="text/css" id="skinSheet">
    <script src="~/Scripts/jquery.dynatree.js" type="text/javascript"></script>
    <script src="~/Member/TreeScript/@Model.Id" type="text/javascript"></script>

}